"""add_score_url_and_image_hash

Revision ID: 1efe136d3d20
Revises: 6902cdf48398
Create Date: 2026-05-18 21:49:08.696297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1efe136d3d20'
down_revision: Union[str, Sequence[str], None] = '6902cdf48398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_results', sa.Column('score_url', sa.String(), nullable=True))
    op.add_column('detection_results', sa.Column('image_pair_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection_results', 'image_pair_hash')
    op.drop_column('detection_results', 'score_url')
    # ### end Alembic commands ###
