import io, re

p = r'D:/A汤福连的比赛与实验/BIT_CD/.claude/tex_parts/g6.tex'
s = io.open(p, encoding='utf-8').read()

print('fig_begin', len(re.findall(r'\\begin\{figure\}', s)))
print('fig_end', len(re.findall(r'\\end\{figure\}', s)))
print('tab_begin', len(re.findall(r'\\begin\{table\}', s)))
print('tab_end', len(re.findall(r'\\end\{table\}', s)))
print('enumerate', len(re.findall(r'\\begin\{enumerate\}', s)), len(re.findall(r'\\end\{enumerate\}', s)))
print('placeholder', s.count('【图片空位'))
print('ascii_dq', s.count('"'))
print('section', len(re.findall(r'\\section\{', s)))
print('subsection', len(re.findall(r'\\subsection\{', s)))
print('chinese', len(re.findall(r'[\u4e00-\u9fff]', s)))
print('chars', len(s))
print('cite', re.findall(r'\\cite\{[^}]*\}', s))
print('label', re.findall(r'\\label\{[^}]*\}', s))
print('caption', re.findall(r'\\caption\{[^}]*\}', s))
print('images', sorted(set(re.findall(r'image\d+\.\w+', s))))
print('imagecount', len(re.findall(r'image\d+\.\w+', s)))
print('refcmd', re.findall(r'\\ref\{[^}]*\}', s))
print('percent_escaped', len(re.findall(r'\\%', s)), 'bare_percent', len(re.findall(r'(?<!\\)%', s)))
print('dollar_count', s.count('$'))
print('amp', len(re.findall(r'(?<!\\)&', s)))
